server:  port: 7099
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ojas_obs_psa
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
eureka: client:   serviceUrl:   defaultZone: http://192.168.1.155:8089/eureka   
spring:
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/obs_psa
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari :       connection-timeout : 500      maximum-pool-size : 2


## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database

  jpa:
    properties:
      hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)

  
    hibernate.ddl-auto : update