#server:
#    port: 5555
#    
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    hikari : 
#      connection-timeout : 500
#      maximum-pool-size : 2
#   url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7074

eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.155:8089/eureka
   
spring:
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/obs_psa
    username: dbubora
    password: Ojas-1525
    driver-class-name: "com.mysql.jdbc.Driver"
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true