server:
  port: 8014
eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.48:8089/eureka
spring:
  datasource:
    #url:  jdbc:mysql://localhost:3306/ojasstates
    #username: root
    #password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.48:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2  