server:
  port: 8099
  
eureka:
 client: 
  serviceUrl:
   defaultZone: http://${GATEWAY_URL}:8081/eureka
   
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/ojas_obs
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
      

#    url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

mailusername: pabbanaveen12@gmail.com
mailpassword: 1311411919
smtphost: mail.smtp.host
mailType: smtp.gmail.com
mailport: mail.smtp.port
mailportNo: 587
mailauth: mail.smtp.auth
mailauthboolean: true
mailsmtpstarttls: mail.smtp.starttls.enable
mailstarttlsenable: true