
server:
  port: 7100

eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.155:8089/eureka
   
spring:
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/obs_rmg
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
     ddl-auto: update
    generate-ddl: true
    show-sql: true
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  
  mail:
    ccEmail : staff_aug@ojas-it.com
    host: smtp.office365.com
    port: 587
    username: support-obs@ojas-it.com
    password: Ojas_OBS
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            trust : smtp.office365.com

    