
server:
  port: 7100
eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.48:8089/eureka  
spring:
  datasource:
    url: jdbc:mysql://192.168.1.48:3306/obs_rmg
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
     ddl-auto: update
     generate-ddl: true
     show-sql: true
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  
  mail:
    toEmail : Anusha.kota@ojas-it.com
    ccEmail : jyothi.medi@ojas-it.com
    bccEmail: 
    host: smtp.office365.com
    port: 587
    username: support-obs@ojas-it.com
    password: Ojas-1525
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            trust : smtp.office365.com

    