server:
  port: 7072
spring:
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/obs_psa
    username: dbubora
    password: Ojas-1525
    driver-class-name: "com.mysql.jdbc.Driver"
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
  mail:
    host: smtp.office365.com
    port: 587
    username: support-obs@ojas-it.com
    password: Ojas_OBS
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false

financemail: ojas_finance@ojas-it.com
db.url: jdbc:mysql://192.168.1.155:3306/ojas_obs