#server:
#  port: 7070
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ojas_obs?autoReconnect=true&useSSL=false
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
    
    #resetUrl: http://192.168.1.155:8000/set

   
#  mail:
#   ccEmail : anusha.kota@ojas-it.com
#   host: smtp.office365.com
#   port: 587
#   username: support-obs@ojas-it.com
#   password: Ojas-1525
#   properties:
#    mail: 
#      smtp: 
#        auth: true
#        starttls: 
#          enable: true
#          trust :


server:
 port: 7070

eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.155:8089/eureka
   
spring:
 datasource:
    url: jdbc:mysql://192.168.1.155:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 
   

 mail:
   ccEmail : ojas_hr@ojas-it.com
   host: smtp.office365.com
   port: 587
   username: support-obs@ojas-it.com
   password: Ojas_OBS
   properties:
    mail: 
     smtp: 
       ssl.trust: smtp.office365.com
       auth: true
       starttls: 
         enable: true
