server:
    port: 9000
    
eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.48:8089/eureka    
    
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.48:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 