server:
    port: 9000
    
spring:
  datasource:
      url: jdbc:mysql://52.188.186.190:3306/ojas_obs
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: dbubora
      password: Ojas-1525
      profiles:
         active:dev  