server:
  port: 7087
  
eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.155:8089/eureka
   
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/obs-cms
#    password: root
#    username: root
#    driver-class-name: "com.mysql.jdbc.Driver"
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true 
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/obs_psa
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari :
      connection-timeout : 500
      maximum-pool-size : 2
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true