

# Here 'test' is the database name

server:
  port: 8088

eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.155:8089/eureka
   
resetUrl: https://www.ojasobs.com/#/index/forgotpassword
siteUrl : http://www.ojasobs.com/#/login

spring:
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2

#    url: jdbc:mysql://localhost:3306/ojas_obs
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

  mail:
    host: smtp.office365.com
    port: 587
    username: support-obs@ojas-it.com
    password: Ojas_OBS
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
