

# Here 'test' is the database name

server:
  port: 8088
resetUrl: http://192.168.1.48:8000/#/forgot
siteUrl : http://192.168.1.48:8000/#/login

eureka:
 client: 
  serviceUrl:
   defaultZone: http://${GATEWAY_URL}:8081/eureka
   
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/ojas_obs
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
#    url: jdbc:mysql://localhost:3306/ojas_obs
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: manohartestmail523@gmail.com
    password: Mytestmail
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true