

# Here 'test' is the database name

server:
  port: 8093

eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.155:8089/eureka
   
spring:
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/ojas_obs?useSSL=false
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
  
  mail:
    host: smtp.office365.com
    port: 587
    username: support-obs@ojas-it.com
    password: Ojas_OBS
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
#    url: jdbc:mysql://localhost:3306/ojas_obs
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver

password: Ojas1525
role: 3
obsUrl: https://www.ojasobs.com
