# MySQL jdbc connection url.
server:
  port: 8083

eureka:
 client: 
  serviceUrl:
   defaultZone: http://${GATEWAY_URL}:8081/eureka
   
spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/ojas_obs
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2
#   url: jdbc:mysql://localhost:3306/obs
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver
   
   