# MySQL jdbc connection url.
server:
  port: 8083

spring :
  datasource :
  
    url: jdbc:mysql://52.188.186.190:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 
#   url: jdbc:mysql://localhost:3306/obs
#   username: root
#   password: root
#   driver-class-name: com.mysql.cj.jdbc.Driver
   
   