server:  port: 7097eureka:  client:    serviceUrl:     defaultZone: http://192.168.1.48:8089/eureka   
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/obs-cms
#    password: root
#    username: root
#    driver-class-name: "com.mysql.jdbc.Driver"  datasource:    url: jdbc:mysql://192.168.1.48:3306/obs_psa    username: dbubora    password: Ojas-1525    driver-class-name: com.mysql.jdbc.Driver    hikari :       connection-timeout : 500      maximum-pool-size : 2 
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true  jackson.serialization.FAIL_ON_EMPTY_BEANS: false    mail:    toEmail : saritha.ummani@ojas-it.com    ccEmail : sravani.ch@ojas-it.com#    bccEmail : Anusha.kota@ojas-it.com    host: smtp.office365.com    port: 587    username: support-obs@ojas-it.com    password: Ojas-1525    properties:      mail:        smtp:          auth: true          starttls:            enable: true            trust : smtp.office365.comsubject: Customer Submission Statussubmit:  Customer created successfully and it is in pending for approval.accept:  Customer has been accepted successfully!reject:  Customer has been rejected. Please update and recreated it.                       