server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://52.188.186.190:3306/ojas_obs
    username: dbubora
    password: Ojas-1525
    driver-class-name: com.mysql.jdbc.Driver
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 
  # url: jdbc:mysql://localhost:3306/ojas_obs
  # username: root
  # password: root
  # driver-class-name: com.mysql.cj.jdbc.Driver

mailname: pabbanaveen12@gmail.com
mailpass: 1311411919
smtphost: mail.smtp.host
mailType: smtp.gmail.com
mailport: mail.smtp.port
mailportNo: 587
mailauth: mail.smtp.auth
mailauthboolean: true
mailsmtpstarttls: mail.smtp.starttls.enable
mailstarttlsenable: true
hrmail: ajaykumar.nagulapati@ojas-it.com
#Auth: true
#Starttlsenable: true
#Host: smtp.office365.com
#Port: 587