server:
  port: 7098

eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.155:8089/eureka
   
spring:
  datasource:
    url: jdbc:mysql://192.168.1.155:3306/obs_psa
    password: Ojas-1525
    username: dbubora
    driver-class-name: "com.mysql.jdbc.Driver"
    hikari : 
      connection-timeout : 500
      maximum-pool-size : 2 
  mail:
     host: smtp.office365.com
     port: 587
     username: support-obs@ojas-it.com
     password: Ojas_OBS
     properties:
       mail: 
         smtp: 
           auth: true
           starttls: 
             enable: true    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
hremail: ojas_hr@ojas-it.com
financemail: ojas_finance@ojas-it.com
db.url: jdbc:mysql://192.168.1.155:3306/ojas_obs


#server:
#  port: 9999
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/obs-psa
#    password: root
#    username: root
#    driver-class-name: "com.mysql.jdbc.Driver"
#  mail:
#    host: smtp.office365.com
#    port: 587
#    username: support-obs@ojas-it.com
#    password: Ojas1525
#    properties:
#      mail: 
#        smtp: 
#          auth: true
#          starttls: 
#            enable: true
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
#hremail: saritha.ummani@ojas-it.com
#financemail: murali.chilabandla@ojas-it.com
#db.url: jdbc:mysql://localhost:3306/ojas_obs    



#jackson.serialization.FAIL_ON_EMPTY_BEANS: false    