server:
  port: 7071
  
eureka:
 client: 
  serviceUrl:
   defaultZone: http://192.168.1.48:8089/eureka      
spring:
  datasource:
    url: jdbc:mysql://192.168.1.48:3306/obs_tms
    username: dbubora
    password: Ojas-1525

    driver-class-name: "com.mysql.jdbc.Driver"
  mail:
    host: smtp.office365.com
    port: 587
    username: support-obs@ojas-it.com
    password: Ojas-1525
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false
  feign.client.url.TestUrl: http://192.168.1.48:8089/obs/employeeInfo/get
file_directory : \home\ojas\Timesheets-uploads\
subject: Timesheet Submission Status
submit: has been submitted successfully and it is in pending for approval.
accept: has been accepted successfully!
reject: Please update and resubmit your timesheet.



